name: Production CI/CD

on:
  push:
    branches:
      - master

jobs:
  start:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: AWS SSM Send Command
        uses: the-wunmi/aws-ssm-send-command@master
        with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID  }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY  }}
            aws-region: us-east-2
            instance-ids: ${{ secrets.INSTANCE_ID  }}
            comment: Deploy the master branch
            check-status-frequency: 10
            max-status-check: 6
            working-directory: /
            command: runuser -l ubuntu -c 'cd ${{ github.event.repository.name }} && /bin/bash ./deploy/deploy.sh'
